api_platform:
    title: 'Memolidays_api'
    description: 'A Symfony API to manage Memolidays app.'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # formats:
    #     jsonld:   ['application/ld+json']
    #     jsonapi:  ['application/vnd.api+json']
    #     json:     ['application/json']
    patch_formats:
        json:     ['application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 200
